/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedBancaRouteImport } from './routes/_authenticated/banca'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminSslRouteImport } from './routes/_authenticated/admin/ssl'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin/backup'
import { Route as AuthenticatedAdminApisRouteImport } from './routes/_authenticated/admin/apis'
import { Route as ApiPublicWebhooksAsaasRouteImport } from './routes/api/public/webhooks/asaas'
import { Route as ApiPublicPaymentsInfinitepayRouteImport } from './routes/api/public/payments/infinitepay'
import { Route as ApiPublicHooksSyncOddsDiarioRouteImport } from './routes/api/public/hooks/sync-odds-diario'
import { Route as ApiPublicHooksSyncFootballRouteImport } from './routes/api/public/hooks/sync-football'
import { Route as ApiPublicHooksGerarBilhetesRouteImport } from './routes/api/public/hooks/gerar-bilhetes'
import { Route as ApiPublicHooksAutoBackupRouteImport } from './routes/api/public/hooks/auto-backup'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBancaRoute = AuthenticatedBancaRouteImport.update({
  id: '/banca',
  path: '/banca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSslRoute = AuthenticatedAdminSslRouteImport.update({
  id: '/ssl',
  path: '/ssl',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminApisRoute = AuthenticatedAdminApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicWebhooksAsaasRoute = ApiPublicWebhooksAsaasRouteImport.update({
  id: '/api/public/webhooks/asaas',
  path: '/api/public/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsInfinitepayRoute =
  ApiPublicPaymentsInfinitepayRouteImport.update({
    id: '/api/public/payments/infinitepay',
    path: '/api/public/payments/infinitepay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncOddsDiarioRoute =
  ApiPublicHooksSyncOddsDiarioRouteImport.update({
    id: '/api/public/hooks/sync-odds-diario',
    path: '/api/public/hooks/sync-odds-diario',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncFootballRoute =
  ApiPublicHooksSyncFootballRouteImport.update({
    id: '/api/public/hooks/sync-football',
    path: '/api/public/hooks/sync-football',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGerarBilhetesRoute =
  ApiPublicHooksGerarBilhetesRouteImport.update({
    id: '/api/public/hooks/gerar-bilhetes',
    path: '/api/public/hooks/gerar-bilhetes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoBackupRoute =
  ApiPublicHooksAutoBackupRouteImport.update({
    id: '/api/public/hooks/auto-backup',
    path: '/api/public/hooks/auto-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/banca': typeof AuthenticatedBancaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/admin/apis': typeof AuthenticatedAdminApisRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/ssl': typeof AuthenticatedAdminSslRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
  '/api/public/hooks/gerar-bilhetes': typeof ApiPublicHooksGerarBilhetesRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
  '/api/public/hooks/sync-odds-diario': typeof ApiPublicHooksSyncOddsDiarioRoute
  '/api/public/payments/infinitepay': typeof ApiPublicPaymentsInfinitepayRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/banca': typeof AuthenticatedBancaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/apis': typeof AuthenticatedAdminApisRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/ssl': typeof AuthenticatedAdminSslRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
  '/api/public/hooks/gerar-bilhetes': typeof ApiPublicHooksGerarBilhetesRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
  '/api/public/hooks/sync-odds-diario': typeof ApiPublicHooksSyncOddsDiarioRoute
  '/api/public/payments/infinitepay': typeof ApiPublicPaymentsInfinitepayRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/banca': typeof AuthenticatedBancaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/apis': typeof AuthenticatedAdminApisRoute
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/ssl': typeof AuthenticatedAdminSslRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
  '/api/public/hooks/gerar-bilhetes': typeof ApiPublicHooksGerarBilhetesRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
  '/api/public/hooks/sync-odds-diario': typeof ApiPublicHooksSyncOddsDiarioRoute
  '/api/public/payments/infinitepay': typeof ApiPublicPaymentsInfinitepayRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/banca'
    | '/perfil'
    | '/planos'
    | '/admin/apis'
    | '/admin/backup'
    | '/admin/configuracoes'
    | '/admin/ssl'
    | '/admin/usuarios'
    | '/api/public/ingest'
    | '/admin/'
    | '/api/public/hooks/auto-backup'
    | '/api/public/hooks/gerar-bilhetes'
    | '/api/public/hooks/sync-football'
    | '/api/public/hooks/sync-odds-diario'
    | '/api/public/payments/infinitepay'
    | '/api/public/webhooks/asaas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/banca'
    | '/perfil'
    | '/planos'
    | '/'
    | '/admin/apis'
    | '/admin/backup'
    | '/admin/configuracoes'
    | '/admin/ssl'
    | '/admin/usuarios'
    | '/api/public/ingest'
    | '/admin'
    | '/api/public/hooks/auto-backup'
    | '/api/public/hooks/gerar-bilhetes'
    | '/api/public/hooks/sync-football'
    | '/api/public/hooks/sync-odds-diario'
    | '/api/public/payments/infinitepay'
    | '/api/public/webhooks/asaas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/banca'
    | '/_authenticated/perfil'
    | '/_authenticated/planos'
    | '/_authenticated/'
    | '/_authenticated/admin/apis'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/ssl'
    | '/_authenticated/admin/usuarios'
    | '/api/public/ingest'
    | '/_authenticated/admin/'
    | '/api/public/hooks/auto-backup'
    | '/api/public/hooks/gerar-bilhetes'
    | '/api/public/hooks/sync-football'
    | '/api/public/hooks/sync-odds-diario'
    | '/api/public/payments/infinitepay'
    | '/api/public/webhooks/asaas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicHooksAutoBackupRoute: typeof ApiPublicHooksAutoBackupRoute
  ApiPublicHooksGerarBilhetesRoute: typeof ApiPublicHooksGerarBilhetesRoute
  ApiPublicHooksSyncFootballRoute: typeof ApiPublicHooksSyncFootballRoute
  ApiPublicHooksSyncOddsDiarioRoute: typeof ApiPublicHooksSyncOddsDiarioRoute
  ApiPublicPaymentsInfinitepayRoute: typeof ApiPublicPaymentsInfinitepayRoute
  ApiPublicWebhooksAsaasRoute: typeof ApiPublicWebhooksAsaasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banca': {
      id: '/_authenticated/banca'
      path: '/banca'
      fullPath: '/banca'
      preLoaderRoute: typeof AuthenticatedBancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ssl': {
      id: '/_authenticated/admin/ssl'
      path: '/ssl'
      fullPath: '/admin/ssl'
      preLoaderRoute: typeof AuthenticatedAdminSslRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/apis': {
      id: '/_authenticated/admin/apis'
      path: '/apis'
      fullPath: '/admin/apis'
      preLoaderRoute: typeof AuthenticatedAdminApisRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/webhooks/asaas': {
      id: '/api/public/webhooks/asaas'
      path: '/api/public/webhooks/asaas'
      fullPath: '/api/public/webhooks/asaas'
      preLoaderRoute: typeof ApiPublicWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/infinitepay': {
      id: '/api/public/payments/infinitepay'
      path: '/api/public/payments/infinitepay'
      fullPath: '/api/public/payments/infinitepay'
      preLoaderRoute: typeof ApiPublicPaymentsInfinitepayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-odds-diario': {
      id: '/api/public/hooks/sync-odds-diario'
      path: '/api/public/hooks/sync-odds-diario'
      fullPath: '/api/public/hooks/sync-odds-diario'
      preLoaderRoute: typeof ApiPublicHooksSyncOddsDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-football': {
      id: '/api/public/hooks/sync-football'
      path: '/api/public/hooks/sync-football'
      fullPath: '/api/public/hooks/sync-football'
      preLoaderRoute: typeof ApiPublicHooksSyncFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/gerar-bilhetes': {
      id: '/api/public/hooks/gerar-bilhetes'
      path: '/api/public/hooks/gerar-bilhetes'
      fullPath: '/api/public/hooks/gerar-bilhetes'
      preLoaderRoute: typeof ApiPublicHooksGerarBilhetesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-backup': {
      id: '/api/public/hooks/auto-backup'
      path: '/api/public/hooks/auto-backup'
      fullPath: '/api/public/hooks/auto-backup'
      preLoaderRoute: typeof ApiPublicHooksAutoBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminApisRoute: typeof AuthenticatedAdminApisRoute
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminSslRoute: typeof AuthenticatedAdminSslRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminApisRoute: AuthenticatedAdminApisRoute,
    AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminSslRoute: AuthenticatedAdminSslRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBancaRoute: typeof AuthenticatedBancaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBancaRoute: AuthenticatedBancaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicHooksAutoBackupRoute: ApiPublicHooksAutoBackupRoute,
  ApiPublicHooksGerarBilhetesRoute: ApiPublicHooksGerarBilhetesRoute,
  ApiPublicHooksSyncFootballRoute: ApiPublicHooksSyncFootballRoute,
  ApiPublicHooksSyncOddsDiarioRoute: ApiPublicHooksSyncOddsDiarioRoute,
  ApiPublicPaymentsInfinitepayRoute: ApiPublicPaymentsInfinitepayRoute,
  ApiPublicWebhooksAsaasRoute: ApiPublicWebhooksAsaasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
