/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicHooksSyncOddsDiarioRouteImport } from './routes/api/public/hooks/sync-odds-diario'
import { Route as ApiPublicHooksSyncFootballRouteImport } from './routes/api/public/hooks/sync-football'
import { Route as ApiPublicHooksGerarBilhetesRouteImport } from './routes/api/public/hooks/gerar-bilhetes'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncOddsDiarioRoute =
  ApiPublicHooksSyncOddsDiarioRouteImport.update({
    id: '/api/public/hooks/sync-odds-diario',
    path: '/api/public/hooks/sync-odds-diario',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncFootballRoute =
  ApiPublicHooksSyncFootballRouteImport.update({
    id: '/api/public/hooks/sync-football',
    path: '/api/public/hooks/sync-football',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGerarBilhetesRoute =
  ApiPublicHooksGerarBilhetesRouteImport.update({
    id: '/api/public/hooks/gerar-bilhetes',
    path: '/api/public/hooks/gerar-bilhetes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/hooks/gerar-bilhetes': typeof ApiPublicHooksGerarBilhetesRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
  '/api/public/hooks/sync-odds-diario': typeof ApiPublicHooksSyncOddsDiarioRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/hooks/gerar-bilhetes': typeof ApiPublicHooksGerarBilhetesRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
  '/api/public/hooks/sync-odds-diario': typeof ApiPublicHooksSyncOddsDiarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/hooks/gerar-bilhetes': typeof ApiPublicHooksGerarBilhetesRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
  '/api/public/hooks/sync-odds-diario': typeof ApiPublicHooksSyncOddsDiarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/ingest'
    | '/api/public/hooks/gerar-bilhetes'
    | '/api/public/hooks/sync-football'
    | '/api/public/hooks/sync-odds-diario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/ingest'
    | '/api/public/hooks/gerar-bilhetes'
    | '/api/public/hooks/sync-football'
    | '/api/public/hooks/sync-odds-diario'
  id:
    | '__root__'
    | '/_authenticated/'
    | '/api/public/ingest'
    | '/api/public/hooks/gerar-bilhetes'
    | '/api/public/hooks/sync-football'
    | '/api/public/hooks/sync-odds-diario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicHooksGerarBilhetesRoute: typeof ApiPublicHooksGerarBilhetesRoute
  ApiPublicHooksSyncFootballRoute: typeof ApiPublicHooksSyncFootballRoute
  ApiPublicHooksSyncOddsDiarioRoute: typeof ApiPublicHooksSyncOddsDiarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-odds-diario': {
      id: '/api/public/hooks/sync-odds-diario'
      path: '/api/public/hooks/sync-odds-diario'
      fullPath: '/api/public/hooks/sync-odds-diario'
      preLoaderRoute: typeof ApiPublicHooksSyncOddsDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-football': {
      id: '/api/public/hooks/sync-football'
      path: '/api/public/hooks/sync-football'
      fullPath: '/api/public/hooks/sync-football'
      preLoaderRoute: typeof ApiPublicHooksSyncFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/gerar-bilhetes': {
      id: '/api/public/hooks/gerar-bilhetes'
      path: '/api/public/hooks/gerar-bilhetes'
      fullPath: '/api/public/hooks/gerar-bilhetes'
      preLoaderRoute: typeof ApiPublicHooksGerarBilhetesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicHooksGerarBilhetesRoute: ApiPublicHooksGerarBilhetesRoute,
  ApiPublicHooksSyncFootballRoute: ApiPublicHooksSyncFootballRoute,
  ApiPublicHooksSyncOddsDiarioRoute: ApiPublicHooksSyncOddsDiarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
