/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicHooksSyncOddsDiarioRouteImport } from './routes/api/public/hooks/sync-odds-diario'
import { Route as ApiPublicHooksSyncFootballRouteImport } from './routes/api/public/hooks/sync-football'
import { Route as ApiPublicHooksGerarBilhetesRouteImport } from './routes/api/public/hooks/gerar-bilhetes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncOddsDiarioRoute =
  ApiPublicHooksSyncOddsDiarioRouteImport.update({
    id: '/api/public/hooks/sync-odds-diario',
    path: '/api/public/hooks/sync-odds-diario',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncFootballRoute =
  ApiPublicHooksSyncFootballRouteImport.update({
    id: '/api/public/hooks/sync-football',
    path: '/api/public/hooks/sync-football',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGerarBilhetesRoute =
  ApiPublicHooksGerarBilhetesRouteImport.update({
    id: '/api/public/hooks/gerar-bilhetes',
    path: '/api/public/hooks/gerar-bilhetes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/hooks/gerar-bilhetes': typeof ApiPublicHooksGerarBilhetesRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
  '/api/public/hooks/sync-odds-diario': typeof ApiPublicHooksSyncOddsDiarioRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/hooks/gerar-bilhetes': typeof ApiPublicHooksGerarBilhetesRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
  '/api/public/hooks/sync-odds-diario': typeof ApiPublicHooksSyncOddsDiarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/hooks/gerar-bilhetes': typeof ApiPublicHooksGerarBilhetesRoute
  '/api/public/hooks/sync-football': typeof ApiPublicHooksSyncFootballRoute
  '/api/public/hooks/sync-odds-diario': typeof ApiPublicHooksSyncOddsDiarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/public/ingest'
    | '/api/public/hooks/gerar-bilhetes'
    | '/api/public/hooks/sync-football'
    | '/api/public/hooks/sync-odds-diario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/api/public/ingest'
    | '/api/public/hooks/gerar-bilhetes'
    | '/api/public/hooks/sync-football'
    | '/api/public/hooks/sync-odds-diario'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/api/public/ingest'
    | '/api/public/hooks/gerar-bilhetes'
    | '/api/public/hooks/sync-football'
    | '/api/public/hooks/sync-odds-diario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicHooksGerarBilhetesRoute: typeof ApiPublicHooksGerarBilhetesRoute
  ApiPublicHooksSyncFootballRoute: typeof ApiPublicHooksSyncFootballRoute
  ApiPublicHooksSyncOddsDiarioRoute: typeof ApiPublicHooksSyncOddsDiarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-odds-diario': {
      id: '/api/public/hooks/sync-odds-diario'
      path: '/api/public/hooks/sync-odds-diario'
      fullPath: '/api/public/hooks/sync-odds-diario'
      preLoaderRoute: typeof ApiPublicHooksSyncOddsDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-football': {
      id: '/api/public/hooks/sync-football'
      path: '/api/public/hooks/sync-football'
      fullPath: '/api/public/hooks/sync-football'
      preLoaderRoute: typeof ApiPublicHooksSyncFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/gerar-bilhetes': {
      id: '/api/public/hooks/gerar-bilhetes'
      path: '/api/public/hooks/gerar-bilhetes'
      fullPath: '/api/public/hooks/gerar-bilhetes'
      preLoaderRoute: typeof ApiPublicHooksGerarBilhetesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicHooksGerarBilhetesRoute: ApiPublicHooksGerarBilhetesRoute,
  ApiPublicHooksSyncFootballRoute: ApiPublicHooksSyncFootballRoute,
  ApiPublicHooksSyncOddsDiarioRoute: ApiPublicHooksSyncOddsDiarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
